/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import Controlador.ControladorTorneo;
import modelos.Torneo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static vista.PerfilU.TextApellido;
import static vista.PerfilU.TextNombre;

/**
 *
 * @author PC
 */
public class Torneos extends javax.swing.JFrame {

    DefaultTableModel modelo;
    ControladorTorneo control = new ControladorTorneo();   

    /**
     * Creates new form Torneo
     */
    public Torneos() {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Administracion de torneos de una cancha sintetica");
        inicio();
        jNom.setText(TextNombre.getText());
        jApe.setText(TextApellido.getText());
    }
    
    public void inicio(){
        tablaModelo();
        cargatabla();
    }
    
    //METODOS PARA MANEJAR LAS TABLAS
     public void cargarTorneo() {
        Torneo torneo = null;
        if (this.tablaTorneo.isEnabled()) {
            int selectedRow = this.tablaTorneo.getSelectedRow();
            
            String nombre = modelo.getValueAt(selectedRow, 0).toString();
            
            //buscamos a ese torneo para traer su id
            torneo = control.obtenerTorneoNombre(nombre);
            Integer num = torneo.getNumeroEquipos();
            control.id_tor = torneo;
            control.numEquipos = num;
            
        }
    }

    public void tablaModelo() {
        //damos los parametros que se veran reflejados en la tabla
        tablaTorneo.getColumnModel().getColumn(0).setPreferredWidth(40);
        tablaTorneo.getColumnModel().getColumn(0).setPreferredWidth(40);
        
        modelo = (DefaultTableModel) tablaTorneo.getModel();
        modelo.setNumRows(0);
    }

    public void cargatabla() {
        //añadimos a traves de una lista los datos a la tabla
        List<Torneo> lista = control.listarTorneo();

        for (Torneo actlist : lista) {
            
            String nombre = String.valueOf(actlist.getNombreTorneo());
            String a = String.valueOf(actlist.getNumeroEquipos());   
            modelo.addRow(new Object[]{ nombre, a,});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTorneo = new javax.swing.JTable();
        btnVer = new javax.swing.JButton();
        F4 = new javax.swing.JLabel();
        jNom = new javax.swing.JLabel();
        jApe = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo.setText("ADMINISTRACION DE TORNEOS");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 290, 50));

        tablaTorneo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Num Equipos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTorneo);
        if (tablaTorneo.getColumnModel().getColumnCount() > 0) {
            tablaTorneo.getColumnModel().getColumn(0).setResizable(false);
            tablaTorneo.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 310, 100));

        btnVer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        btnVer.setText("Mostrar");
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 120, 30));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 310));

        jNom.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 20));

        jApe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(jApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 20));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, 310));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 120, 310));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPaginas.jpg"))); // NOI18N
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        // llamamos el cargar torneo
      
       
             cargarTorneo();
             dispose();     
               Equipos v_Equipos = new Equipos();
             v_Equipos.setVisible(true);
       

       
    }//GEN-LAST:event_btnVerMouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Torneos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Torneos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jApe;
    private javax.swing.JLabel jNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTorneo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
